# Form implementation generated from reading ui file '.\server_ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReceiveServerForm(object):
    def setupUi(self, ReceiveServerForm):
        ReceiveServerForm.setObjectName("ReceiveServerForm")
        ReceiveServerForm.resize(749, 489)
        ReceiveServerForm.setStyleSheet("QGroupBox {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 rgb(222, 233, 255), stop: 1 #FFFFFF);\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    border: 1px solid grey;\n"
"    padding: 0 3px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #aaaaff, stop: 1 #FFFFFF);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid grey;\n"
"    border-radius: 3px;\n"
"    background-color:rgba(170, 170, 255, 50);\n"
"    padding: 3px;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color: black;\n"
"    background-color:rgba(170, 170, 255, 100);\n"
"}\n"
"QPushButton:hover {\n"
"    border-color: black;\n"
"}")
        self.imageGroup = QtWidgets.QGroupBox(parent=ReceiveServerForm)
        self.imageGroup.setGeometry(QtCore.QRect(310, 10, 431, 471))
        self.imageGroup.setStyleSheet("")
        self.imageGroup.setFlat(False)
        self.imageGroup.setCheckable(False)
        self.imageGroup.setObjectName("imageGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.imageGroup)
        self.gridLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.imageLabel = QtWidgets.QLabel(parent=self.imageGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMaximumSize(QtCore.QSize(400, 400))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(r"..\UI\noimg.jpg"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout_2.addWidget(self.imageLabel, 1, 0, 1, 2)
        self.pasteImageButton = QtWidgets.QPushButton(parent=self.imageGroup)
        self.pasteImageButton.setObjectName("pasteImageButton")
        self.gridLayout_2.addWidget(self.pasteImageButton, 0, 0, 1, 1)
        self.clearImageButton = QtWidgets.QPushButton(parent=self.imageGroup)
        self.clearImageButton.setObjectName("clearImageButton")
        self.gridLayout_2.addWidget(self.clearImageButton, 0, 1, 1, 1)
        self.textGroup = QtWidgets.QGroupBox(parent=ReceiveServerForm)
        self.textGroup.setGeometry(QtCore.QRect(10, 10, 291, 131))
        self.textGroup.setObjectName("textGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.textGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QLineEdit(parent=self.textGroup)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.pasteTextButton = QtWidgets.QPushButton(parent=self.textGroup)
        self.pasteTextButton.setObjectName("pasteTextButton")
        self.verticalLayout_2.addWidget(self.pasteTextButton)
        self.clearTextButton = QtWidgets.QPushButton(parent=self.textGroup)
        self.clearTextButton.setObjectName("clearTextButton")
        self.verticalLayout_2.addWidget(self.clearTextButton)
        self.dataRecordBox = QtWidgets.QGroupBox(parent=ReceiveServerForm)
        self.dataRecordBox.setGeometry(QtCore.QRect(10, 140, 291, 271))
        self.dataRecordBox.setStyleSheet("")
        self.dataRecordBox.setObjectName("dataRecordBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataRecordBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(parent=self.dataRecordBox)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.dataRecordBox)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.expLabel = QtWidgets.QLabel(parent=self.dataRecordBox)
        self.expLabel.setObjectName("expLabel")
        self.verticalLayout.addWidget(self.expLabel)
        self.expSpin = QtWidgets.QSpinBox(parent=self.dataRecordBox)
        self.expSpin.setProperty("value", 5)
        self.expSpin.setObjectName("expSpin")
        self.verticalLayout.addWidget(self.expSpin)
        self.birthLabel = QtWidgets.QLabel(parent=self.dataRecordBox)
        self.birthLabel.setObjectName("birthLabel")
        self.verticalLayout.addWidget(self.birthLabel)
        self.birthEdit = QtWidgets.QDateEdit(parent=self.dataRecordBox)
        self.birthEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1995, 5, 13), QtCore.QTime(0, 0, 0)))
        self.birthEdit.setObjectName("birthEdit")
        self.verticalLayout.addWidget(self.birthEdit)
        self.pasteRecordButton = QtWidgets.QPushButton(parent=self.dataRecordBox)
        self.pasteRecordButton.setStyleSheet("")
        self.pasteRecordButton.setObjectName("pasteRecordButton")
        self.verticalLayout.addWidget(self.pasteRecordButton)
        self.clearRecordButton = QtWidgets.QPushButton(parent=self.dataRecordBox)
        self.clearRecordButton.setObjectName("clearRecordButton")
        self.verticalLayout.addWidget(self.clearRecordButton)

        self.retranslateUi(ReceiveServerForm)
        QtCore.QMetaObject.connectSlotsByName(ReceiveServerForm)

    def retranslateUi(self, ReceiveServerForm):
        _translate = QtCore.QCoreApplication.translate
        ReceiveServerForm.setWindowTitle(_translate("ReceiveServerForm", "Сервер для приема"))
        self.imageGroup.setTitle(_translate("ReceiveServerForm", "Изображение"))
        self.pasteImageButton.setText(_translate("ReceiveServerForm", "Вставить"))
        self.clearImageButton.setText(_translate("ReceiveServerForm", "Очитстить"))
        self.textGroup.setTitle(_translate("ReceiveServerForm", "Текст"))
        self.textEdit.setText(_translate("ReceiveServerForm", "Какой-то текст"))
        self.pasteTextButton.setText(_translate("ReceiveServerForm", "Вставить"))
        self.clearTextButton.setText(_translate("ReceiveServerForm", "Очитстить"))
        self.dataRecordBox.setTitle(_translate("ReceiveServerForm", "Запись/Структура"))
        self.nameLabel.setText(_translate("ReceiveServerForm", "Имя"))
        self.nameEdit.setText(_translate("ReceiveServerForm", "Иван Иванов"))
        self.expLabel.setText(_translate("ReceiveServerForm", "Стаж"))
        self.birthLabel.setText(_translate("ReceiveServerForm", "Дата Рождения"))
        self.pasteRecordButton.setText(_translate("ReceiveServerForm", "Вставить"))
        self.clearRecordButton.setText(_translate("ReceiveServerForm", "Очитстить"))
